# Generated by Django 2.0.5 on 2018-10-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0002_auto_20180922_1930'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructor',
            unique_together={('last_name', 'first_name')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('semester', 'course', 'section_name')},
        ),
    ]
